buffy:
  env:
    procbuild_url: "https://procbuild.scipy.org"
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
    gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors:
      - deniederhut
      - mepa
      - cbcunc
  responders:
    help:
    hello:
      hidden: true
    thanks:
      hidden: true
    basic_command:
      - code_of_conduct:
          command: code of conduct
          description: Show our community Code of Conduct and Guidelines
          messages:
            - "Our CoC: https://www.scipy2023.scipy.org/code-of-conduct"
            - "Reports of abusive or harassing behavior may be reported to scipy@enthought.com"
    list_of_values:
      - reviewers:
          only: editors
          sample_value: "@username"
          add_as_assignee: true
    assign_editor:
      only: editors
    remove_editor:
      only: editors
      no_editor_text: "TBD"
    # invite:
    #   only: editors
    add_remove_assignee:
      only: editors
    build_paper:
        data_from_issue:
          - issue
    build_status:
        data_from_issue:
          - issue
    check_references:
    label_command:
      - paper:
          command: mark paper
          add_labels:
            - paper
      - needs_review:
          only: editors
          command: mark needs review
          add_labels:
            - needs-review
          remove_labels:
            - unready
            - needs-more-review
            - pending-comment
            - ready
      - needs_more_review:
          only: editors
          command: mark needs more review
          add_labels:
            - needs-more-review
          remove_labels:
            - unready
            - needs-review
            - pending-comment
            - ready
      - pending_comment:
          only: editors
          command: mark pending comment
          add_labels:
            - pending-comment
          remove_labels:
            - unready
            - needs-review
            - needs-more-review
            - ready
      - ready:
          only: editors
          command: mark ready
          add_labels:
            - ready
          remove_labels:
            - unready
            - needs-review
            - needs-more-review
            - pending-comment
      - not_ready:
          only: editors
          command: mark not ready
          add_labels:
            - unready
          remove_labels:
            - needs-review
            - needs-more-review
            - pending-comment
            - ready
      - server_fail:
          command: mark server fail
          add_labels:
            - does_not_build:server
      - server_success:
          command: mark server success
          remove_labels:
            - does_not_build:server
    welcome:
